name: master

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --release --verbose
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: exchange-aggregator
          path: target/release/exchange-aggregator
